# Needs to be moved to %APPDATA%\alacritty\alacritty.toml

[terminal.shell]
program = 'C://Windows/system32/wsl'
args = ["--cd ~"]
#program = 'Ubuntu' # Update for other distribs

[env]
TERM = "xterm-256color"

[general]
import = ["C://Users/<user>/AppData/Roaming/alacritty/catppuccin-frappe.toml"]

[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 1
blur = true

[font]
normal.family = "Hack Nerd Font Mono"
normal.style = "Regular"
size = 10

[cursor]
blink_interval = 500
blink_timeout = 255
[cursor.style]
shape = "Block"
blinking = "Always"
